name: Submit to IndexNow

on:
  push:
    branches: [master]
    paths:
      - 'content/**'
  workflow_dispatch:

jobs:
  indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Submit Sitemap to IndexNow
        uses: bojieyang/indexnow-action@v3
        with:
          sitemap-location: 'https://wjhnow.com/sitemap.xml'
          key: ${{ secrets.INDEXNOW_KEY }}
